/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package arbolE;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;

/**
 *
 * @author jesus
 */
public class FrameGenerador extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameGenerador.class.getName());

    /**
     * Creates new form FrameGenerador
     */
    LocalTime hora = LocalTime.now();
    DateTimeFormatter formateador = DateTimeFormatter.ofPattern("HH:mm:ss");

    public FrameGenerador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSuperior = new javax.swing.JPanel();
        imgLogoTec = new Componentes.ImagenRedondeada();
        lblTítulo = new javax.swing.JLabel();
        imgFoto = new Componentes.ImagenRedondeada();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxtArchivo = new javax.swing.JTextField();
        jTxtEnvio = new javax.swing.JTextField();
        jBtnExportar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        laHora = new javax.swing.JLabel();
        imagenRedondeada1 = new Componentes.ImagenRedondeada();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlSuperior.setBackground(new java.awt.Color(153, 153, 153));

        imgLogoTec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arbolE/escudo_itt_grande.png"))); // NOI18N

        lblTítulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTítulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTítulo.setText("Generador LCD");

        imgFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arbolE/Foto.png"))); // NOI18N

        javax.swing.GroupLayout pnlSuperiorLayout = new javax.swing.GroupLayout(pnlSuperior);
        pnlSuperior.setLayout(pnlSuperiorLayout);
        pnlSuperiorLayout.setHorizontalGroup(
            pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgLogoTec, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141)
                .addComponent(lblTítulo, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imgFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlSuperiorLayout.setVerticalGroup(
            pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSuperiorLayout.createSequentialGroup()
                .addGroup(pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSuperiorLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblTítulo))
                    .addGroup(pnlSuperiorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(imgLogoTec, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSuperiorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(imgFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Nombre archivo");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Mensaje enviar");

        jBtnExportar.setText("Exportar");
        jBtnExportar.addActionListener(this::jBtnExportarActionPerformed);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        laHora.setText("Hora envío: ");

        imagenRedondeada1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arbolE/Captura de pantalla 2026-07-16 112618.png"))); // NOI18N

        jLabel4.setText(".asm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnExportar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(imagenRedondeada1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTxtEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(laHora, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnExportar)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(imagenRedondeada1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(laHora))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExportarActionPerformed
        String nombreArchivo = jTxtArchivo.getText();
        String mensaje = jTxtEnvio.getText();

        String contenidoLCD = contenidoArchivoLCD(mensaje,nombreArchivo);

        jTextArea1.setText(contenidoLCD);
        generaEmutasm(nombreArchivo, contenidoLCD);

        hora = LocalTime.now();
        laHora.setText("Hora envío: " + hora.format(formateador));
        sonido();
        abrirEnEmu8086(nombreArchivo);
    }//GEN-LAST:event_jBtnExportarActionPerformed
    public void generaEmutasm(String nombreArchivo, String contenidoLCD) {
        try {
            FileWriter escritor = new FileWriter(nombreArchivo + ".asm");

            escritor.write(contenidoLCD);
            escritor.close();

            System.out.println("Archivo " + nombreArchivo + ".asm creado exitosamente");
        } catch (Exception e) {
            System.out.println("Ha ocurrido un error al crear el archivo: "+e.getMessage()
            );
        }
    }

    public String contenidoArchivoLCD(String mensaje,String nombreArchivo) { 
        int longitudMensaje = mensaje.length();

        StringBuilder contenidoLCD = new StringBuilder();

        contenidoLCD.append(";Espinosa Benitez Jesus\n");
        contenidoLCD.append("; Guardar como ");
        contenidoLCD.append(nombreArchivo);
        contenidoLCD.append(".asm\n");
        contenidoLCD.append(".model small\n");
        contenidoLCD.append(".stack\n");
        contenidoLCD.append(".data\n");
        contenidoLCD.append("    MENSAJE DB '")
                .append(mensaje)
                .append("'; LONG ")
                .append(longitudMensaje)
                .append("\n");
        contenidoLCD.append(".code\n");
        contenidoLCD.append("    mov ax,@data\n");
        contenidoLCD.append("    mov ds, ax\n");
        contenidoLCD.append("\n");
        contenidoLCD.append("    mov si,0 ; Indice\n");
        contenidoLCD.append("    mov cx,")
                .append(longitudMensaje)
                .append("\n");
        contenidoLCD.append("    mov dx,2040h ; Puerto\n");
        contenidoLCD.append("\n");
        contenidoLCD.append("label01:\n");
        contenidoLCD.append("\n");
        contenidoLCD.append("    mov al,MENSAJE[si]\n");
        contenidoLCD.append("    out dx,al\n");
        contenidoLCD.append("    inc si\n");
        contenidoLCD.append("    inc dx\n");
        contenidoLCD.append("    loop label01\n");
        contenidoLCD.append("\n");
        contenidoLCD.append("    mov ax,4c00h\n");
        contenidoLCD.append("    int 21h\n");
        contenidoLCD.append("END\n");

        return contenidoLCD.toString();
    }
    
    public void sonido() {
        try {
            File sonido = new File("src/arbolE/new-notification-022-370046.wav");

            if (sonido.exists()) {
                AudioInputStream audioStream = AudioSystem.getAudioInputStream(sonido);
                Clip clip = AudioSystem.getClip();
                clip.open(audioStream);
                clip.start();
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró el archivo de sonido.");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al reproducir el sonido.");
        }
    }
    
public void abrirEnEmu8086(String nombreArchivo) {
    try {
        File archivoAsm = new File(nombreArchivo + ".asm");

        if (!archivoAsm.exists()) {
            JOptionPane.showMessageDialog(
                    this,
                    "No se encontró el archivo ASM:\n"
                    + archivoAsm.getAbsolutePath()
            );
            return;
        }
        String rutaEmu8086 = "C:\\emu8086\\emu8086.exe";

        File ejecutableEmu8086 = new File(rutaEmu8086);

        if (!ejecutableEmu8086.exists()) {JOptionPane.showMessageDialog(this,"No se encontró EMU8086 en:\n"+ rutaEmu8086+ "\n\nModifica la variable rutaEmu8086 con la ubicación correcta.");
            return;
        }
        ProcessBuilder proceso = new ProcessBuilder(ejecutableEmu8086.getAbsolutePath(),archivoAsm.getAbsolutePath());

        proceso.start();

    } catch (IOException e) {
        JOptionPane.showMessageDialog(this,"No se pudo abrir el archivo en EMU8086:\n"+ e.getMessage());
    }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrameGenerador().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Componentes.ImagenRedondeada imagenRedondeada1;
    private Componentes.ImagenRedondeada imgFoto;
    private Componentes.ImagenRedondeada imgLogoTec;
    private javax.swing.JButton jBtnExportar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTxtArchivo;
    private javax.swing.JTextField jTxtEnvio;
    private javax.swing.JLabel laHora;
    private javax.swing.JLabel lblTítulo;
    private javax.swing.JPanel pnlSuperior;
    // End of variables declaration//GEN-END:variables
}
