/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package arbolE;

import java.awt.Color;
import javax.swing.JColorChooser;

/**
 *
 * @author jesus
 */
public class FrameArbolDibujado extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameArbolDibujado.class.getName());

    /**
     * Creates new form FrameArbolDibujado
     */
    private PanelArbol panelArbol;

    public FrameArbolDibujado() {
        initComponents();
        configurarFrame();
    }

    private void configurarFrame() {
        configurarSliders();
        configurarBotonesColor();
    }

    private void configurarSliders() {
        sldLineas.addChangeListener(e -> {
            if (panelArbol != null) {
                // Este slider cambia el grosor de todas las líneas:
                // líneas de conexión y contorno de los nodos.
                panelArbol.setAnchoLineas(sldLineas.getValue());
            }
        });

        sldNodos.addChangeListener(e -> {
            if (panelArbol != null) {
                // Este slider cambia el tamaño del círculo del nodo.
                panelArbol.setRadioNodo(sldNodos.getValue());
            }
        });
    }

    private void configurarBotonesColor() {
        btnColorLineas.addActionListener(e -> {
            if (panelArbol == null) {
                return;
            }
            Color nuevoColor = JColorChooser.showDialog(this, "selecciona el color de todas las líneas",panelArbol.getColorLineas()
            );
            if (nuevoColor != null) {//Este botón cambia las líneas de conexión y el contorno de los nodos
                panelArbol.setColorLineas(nuevoColor);
            }
        });

        btnColorNodos.addActionListener(e -> {
            if (panelArbol == null) {
                return;
            }

            Color nuevoColor = JColorChooser.showDialog(this,"selecciona el color de relleno de los nodos",panelArbol.getColorRellenoNodos());

            if (nuevoColor != null) {//Este botón cambia el color del circulito del nodo.
                panelArbol.setColorRellenoNodos(nuevoColor);
            }
        });
    }

    public FrameArbolDibujado(PanelArbol panelArbol) {
        initComponents();
        this.panelArbol = panelArbol;
        configurarFrame();
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sldNodos = new javax.swing.JSlider();
        sldLineas = new javax.swing.JSlider();
        btnColorLineas = new javax.swing.JButton();
        btnColorNodos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Lineas");

        jLabel2.setText("Nodos");

        sldNodos.setMaximum(50);
        sldNodos.setMinimum(1);
        sldNodos.setValue(20);

        sldLineas.setMaximum(30);
        sldLineas.setMinimum(1);
        sldLineas.setValue(2);

        btnColorLineas.setText("Color");

        btnColorNodos.setText("Color");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(63, 63, 63))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(sldLineas, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addGap(53, 53, 53)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnColorLineas, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnColorNodos, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sldNodos, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sldNodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sldLineas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnColorLineas)
                    .addComponent(btnColorNodos))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrameArbolDibujado().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnColorLineas;
    private javax.swing.JButton btnColorNodos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSlider sldLineas;
    private javax.swing.JSlider sldNodos;
    // End of variables declaration//GEN-END:variables
}
