
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package arbolE;

import java.awt.Desktop;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author jesus
 */
public class FrameInterfaz extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameInterfaz.class.getName());

    /**
     * Creates new form FrameInterfaz
     */
    //Atributos -9 de julio
    String nPolaca;

    //10 de julio
    int temp = 0;
    FrameCuadruplos cuadruplos;

    private ArbolIA arbolIA;

    //15 de julio
    Nodo arbolExpresion;
    String izq, der;
    String emuLocal;
    int Contador;

    public FrameInterfaz() {
        initComponents();
        nPolaca = "";

        emuLocal = "";
        izq = der = "";
        Contador = 0;
    }

    public void preOrden(Nodo n) {
        if (n != null) {
            txtPreOrder.append(n.getDato() + "\n");
            nPolaca += txtNotacion.getText() + n.getDato() + " ";
            txtNotacion.setText(txtNotacion.getText() + n.getDato() + " ");
            preOrden(n.getIzquierdo());
            preOrden(n.getDerecho());
        }
    }

    public void inOrden(Nodo n) {
        if (n != null) {
            inOrden(n.getIzquierdo());
            txtInOrder.append(n.getDato() + "\n");
            inOrden(n.getDerecho());
        }
    }//in

    public void postOrden(Nodo n) {
        if (n != null) {
            postOrden(n.getIzquierdo());
            postOrden(n.getDerecho());
            txtPostOrden.append(n.getDato() + "\n");
        }
    }//Post

    private void guardarReglasSemanticas() {
        File archivo = new File("reglasSemanticas.txt");

        try (BufferedWriter escritor = new BufferedWriter(new FileWriter(archivo))) {

            // Guarda en el archivo todo lo que contiene txtReglas
            escritor.write(txtReglas.getText());
            System.out.println("se genero el archivo en: " + archivo.getAbsolutePath());
        } catch (IOException ex) {
            System.out.println("No se pudo generar el archivo reglasSemanticas.txt\n" + ex.getMessage());
        }//catch
    } //guardarReglasSemanticas

    //=======Intermedio
    public void intermedio(Nodo n) {
        if (n != null) {
            intermedio(n.getIzquierdo());
            intermedio(n.getDerecho());
            if (n.getIzquierdo() == null && n.getDerecho() == null) {
                n.setLugar(n.getDato() + " ");
                n.setCodigoIntermedio("");

            } else {
                if (n.getDato().equals("+") || n.getDato().equals("*")
                        || n.getDato().equals("-") || n.getDato().equals("/")) {
                    temp++;
                    n.setLugar("T" + temp);
                    Nodo izquierdo = n.getIzquierdo();
                    Nodo derecho = n.getDerecho();
                    String codigoI = "";
                    codigoI = izquierdo.getCodigoIntermedio() + " " + derecho.getCodigoIntermedio() + " " + n.getLugar() + " = "
                            + izquierdo.getLugar() + n.getDato() + " " + derecho.getLugar();
                    n.setCodigoIntermedio(codigoI + "\n");
                } else {
                    if (n.getDato().equals("=")) {
                        String codigoI = "";
                        Nodo izquierdo = n.getIzquierdo();
                        Nodo derecho = n.getDerecho();
                        codigoI = derecho.getDato() + " " + izquierdo.getLugar() + " = T" + temp + "\n";
                        n.setCodigoIntermedio(codigoI);
                    }//equals =
                }//equals +-*/
            }//getDer getIzq
        }//n!=null
    }//intermedio

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblExpresion = new javax.swing.JLabel();
        txtExpresion = new javax.swing.JTextField();
        btnCompilar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPreOrder = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCodigo3Dir = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtInOrder = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtPostOrden = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtReglas = new javax.swing.JTextArea();
        pnlSuperior = new javax.swing.JPanel();
        imgLogoTec = new Componentes.ImagenRedondeada();
        lblTítulo = new javax.swing.JLabel();
        imgFoto = new Componentes.ImagenRedondeada();
        imgLogoCiscoScript = new Componentes.ImagenRedondeada();
        imgLogoPato = new Componentes.ImagenRedondeada();
        pnlMedio = new javax.swing.JPanel();
        lblIn = new javax.swing.JLabel();
        lblPre = new javax.swing.JLabel();
        lblPost = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblReglas = new javax.swing.JLabel();
        pnlInferior = new javax.swing.JPanel();
        lblNotacion = new javax.swing.JLabel();
        txtNotacion = new javax.swing.JTextField();
        btnCodigo = new javax.swing.JButton();
        btnClean = new javax.swing.JButton();
        btnTabla = new javax.swing.JButton();
        btnGDA = new javax.swing.JButton();
        btnAgenteIA = new javax.swing.JButton();
        btnOptimizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblExpresion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblExpresion.setText("Expresión");

        txtExpresion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnCompilar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCompilar.setText("Compilar");
        btnCompilar.addActionListener(this::btnCompilarActionPerformed);

        txtPreOrder.setColumns(20);
        txtPreOrder.setRows(5);
        jScrollPane1.setViewportView(txtPreOrder);

        txtCodigo3Dir.setColumns(20);
        txtCodigo3Dir.setRows(5);
        jScrollPane2.setViewportView(txtCodigo3Dir);

        txtInOrder.setColumns(20);
        txtInOrder.setRows(5);
        jScrollPane3.setViewportView(txtInOrder);

        txtPostOrden.setColumns(20);
        txtPostOrden.setRows(5);
        jScrollPane4.setViewportView(txtPostOrden);

        txtReglas.setColumns(20);
        txtReglas.setRows(5);
        jScrollPane5.setViewportView(txtReglas);

        pnlSuperior.setBackground(new java.awt.Color(153, 153, 153));

        imgLogoTec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arbolE/escudo_itt_grande.png"))); // NOI18N

        lblTítulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTítulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTítulo.setText("Árbol de expresiones - LyA II");

        imgFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arbolE/Foto.png"))); // NOI18N

        imgLogoCiscoScript.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arbolE/Logo CiscoS.jpg"))); // NOI18N

        imgLogoPato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arbolE/Logo.png"))); // NOI18N

        javax.swing.GroupLayout pnlSuperiorLayout = new javax.swing.GroupLayout(pnlSuperior);
        pnlSuperior.setLayout(pnlSuperiorLayout);
        pnlSuperiorLayout.setHorizontalGroup(
            pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgLogoTec, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141)
                .addComponent(lblTítulo, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imgLogoPato, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(imgLogoCiscoScript, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(imgFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        pnlSuperiorLayout.setVerticalGroup(
            pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSuperiorLayout.createSequentialGroup()
                .addGroup(pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSuperiorLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblTítulo))
                    .addGroup(pnlSuperiorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(imgLogoTec, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSuperiorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imgLogoCiscoScript, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imgLogoPato, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imgFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMedio.setBackground(new java.awt.Color(255, 204, 51));

        lblIn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblIn.setText("In Orden");

        lblPre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPre.setText("Pre Orden");

        lblPost.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPost.setText("Post Orden");

        lblCodigo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCodigo.setText("Código 3 direcciones");

        lblReglas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblReglas.setText("Reglas semánticas");

        javax.swing.GroupLayout pnlMedioLayout = new javax.swing.GroupLayout(pnlMedio);
        pnlMedio.setLayout(pnlMedioLayout);
        pnlMedioLayout.setHorizontalGroup(
            pnlMedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMedioLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblPre, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(lblIn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(lblPost)
                .addGap(60, 60, 60)
                .addComponent(lblReglas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCodigo)
                .addGap(84, 84, 84))
        );
        pnlMedioLayout.setVerticalGroup(
            pnlMedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMedioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIn)
                    .addComponent(lblPre)
                    .addComponent(lblPost)
                    .addComponent(lblCodigo)
                    .addComponent(lblReglas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlInferior.setBackground(new java.awt.Color(0, 0, 0));

        lblNotacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNotacion.setForeground(new java.awt.Color(255, 255, 255));
        lblNotacion.setText("Notacion Polaca");

        txtNotacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnCodigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCodigo.setText("Código de 3 direcciones");
        btnCodigo.addActionListener(this::btnCodigoActionPerformed);

        btnClean.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnClean.setText("Clean");
        btnClean.addActionListener(this::btnCleanActionPerformed);

        btnTabla.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTabla.setText("Tabla de símbolos");
        btnTabla.addActionListener(this::btnTablaActionPerformed);

        btnGDA.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGDA.setText("GDA");
        btnGDA.addActionListener(this::btnGDAActionPerformed);

        javax.swing.GroupLayout pnlInferiorLayout = new javax.swing.GroupLayout(pnlInferior);
        pnlInferior.setLayout(pnlInferiorLayout);
        pnlInferiorLayout.setHorizontalGroup(
            pnlInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInferiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNotacion, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtNotacion, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGDA, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnClean, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTabla)
                .addGap(16, 16, 16))
        );
        pnlInferiorLayout.setVerticalGroup(
            pnlInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInferiorLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(pnlInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNotacion)
                    .addComponent(txtNotacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCodigo)
                    .addComponent(btnClean)
                    .addComponent(btnTabla)
                    .addComponent(btnGDA))
                .addContainerGap())
        );

        btnAgenteIA.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAgenteIA.setText("Agente IA");
        btnAgenteIA.addActionListener(this::btnAgenteIAActionPerformed);

        btnOptimizar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnOptimizar.setText("Optimizar");
        btnOptimizar.addActionListener(this::btnOptimizarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblExpresion, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtExpresion, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCompilar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAgenteIA, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnOptimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
            .addComponent(pnlSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMedio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlInferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtExpresion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCompilar)
                    .addComponent(btnAgenteIA)
                    .addComponent(lblExpresion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOptimizar))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(pnlMedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanActionPerformed
        txtExpresion.setText("");
        txtCodigo3Dir.setText("");
        txtPreOrder.setText("");
        txtInOrder.setText("");
        txtPostOrden.setText("");
        txtReglas.setText("");
        txtNotacion.setText("");
        arbolIA = null;
        nPolaca = "";
    }//GEN-LAST:event_btnCleanActionPerformed

    private void btnTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTablaActionPerformed
        String datos = txtExpresion.getText();
        if (arbolIA == null) {
            arbolIA = new ArbolIA();
            arbolIA.crear(datos);
        }

        JOptionPane.showMessageDialog(this, arbolIA.tablaSimbolos);
    }//GEN-LAST:event_btnTablaActionPerformed

    private void btnCompilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompilarActionPerformed
        txtCodigo3Dir.setText("");
        txtPreOrder.setText("");
        txtInOrder.setText("");
        txtPostOrden.setText("");
        txtReglas.setText("");
        txtNotacion.setText("");
        String datos = "";
        temp = 0;

        ArbolJesusEspinosa arbol = new ArbolJesusEspinosa();
        datos = txtExpresion.getText();
        Nodo arbolExpresion = arbol.crear(datos); //Enviar los datos al árbol- expresión
        txtReglas.append(arbol.getReglasEjecutadas());
        intermedio(arbolExpresion);

        preOrden(arbolExpresion);
        inOrden(arbolExpresion);
        postOrden(arbolExpresion);
        guardarReglasSemanticas();
        txtCodigo3Dir.append(arbolExpresion.getCodigoIntermedio());
    }//GEN-LAST:event_btnCompilarActionPerformed

    private void btnAgenteIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgenteIAActionPerformed
        txtCodigo3Dir.setText("");
        txtPreOrder.setText("");
        txtInOrder.setText("");
        txtPostOrden.setText("");
        txtReglas.setText("");
        txtNotacion.setText("");
        temp = 0;
        emuLocal = "";
        String datos = txtExpresion.getText();

        //le puse este para que si ya están dados los valores no me los vuelva a pedir, a menos que le de en clean
        if (arbolIA == null) {
            arbolIA = new ArbolIA();
        }

        arbolExpresion = arbolIA.crear(datos);

        txtReglas.append(arbolIA.getReglasEjecutadas());
        intermedio(arbolExpresion);
        generarEmuLocal(arbolExpresion);

        JFrame ventana = new JFrame("Visualizador de Árboles - LyA2");
        PanelArbol panel = new PanelArbol(arbolExpresion);

        ventana.add(panel);
        ventana.setSize(800, 600);
        ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);

        FrameArbolDibujado opcionesArbol = new FrameArbolDibujado(panel);
        opcionesArbol.setVisible(true);

        preOrden(arbolExpresion);
        inOrden(arbolExpresion);
        postOrden(arbolExpresion);
        guardarReglasSemanticas();

        txtCodigo3Dir.append(arbolExpresion.getCodigoIntermedio());

        arbolIA.emu86 += ".code \n"
                + "mov ax,@data \n"
                + "mov ds,ax \n";

        String finalEmu = arbolIA.emu86 + emuLocal;
        finalEmu += "\nmov ax,4c00h \n"
                + "int 21h \n"
                + "end";

        JOptionPane.showMessageDialog(this, finalEmu);
        Contador++;

        String nombreArchivoAsm = "e" + Contador + ".asm";

        generaEmutasm(finalEmu, Contador);
        abrirEnEmu8086(nombreArchivoAsm);
        sonido();

        //mostrar las tripletas gen
        ArrayList<String[]> tripletas = arbolIA.getTripletas();
        FrameTripletas frameTripletas = new FrameTripletas(tripletas);
        frameTripletas.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        frameTripletas.setVisible(true);

        //mostrar los cuádruplos usando la interfaz original de FrameCuadruplos.
        FrameCuadruplos frameCuadruplos = new FrameCuadruplos(arbolExpresion);
        frameCuadruplos.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        frameCuadruplos.setVisible(true);

    }//GEN-LAST:event_btnAgenteIAActionPerformed

    private ArrayList<String[]> crearTripletas(String codigoIntermedio) {
        ArrayList<String[]> tripletas = new ArrayList<>();
        String[] lineas = codigoIntermedio.split("\n");

        for (String linea : lineas) {
            linea = linea.trim();

            if (linea.isEmpty() || !linea.contains("=")) {
                continue;
            }

            String[] partes = linea.split("=", 2);
            String resultado = partes[0].trim();
            String expresion = partes[1].trim();
            String operador = "=";
            String arg1 = expresion;
            String arg2 = resultado;

            for (String posibleOperador : new String[]{"+", "-", "*", "/", "^"}) {
                int posicion = expresion.indexOf(posibleOperador);

                if (posicion > 0) {
                    operador = posibleOperador;
                    arg1 = expresion.substring(0, posicion).trim();
                    arg2 = expresion.substring(posicion + 1).trim();
                    break;
                }
            }

            tripletas.add(new String[]{operador, arg1, arg2});
        }

        return tripletas;
    }

    public void generarEmuLocal(Nodo n) {
        if (n != null) {
            generarEmuLocal(n.getIzquierdo());
            generarEmuLocal(n.getDerecho());

            if (n.getIzquierdo() == null || n.getDerecho() == null) {
                return;
            }

            switch (n.getDato()) {
                case "+":
                    System.out.println("add");
                    izq = n.getIzquierdo().getDato();
                    der = n.getDerecho().getDato();

                    System.out.println("izq: " + izq);
                    System.out.println("der: " + der);
                    emuLocal += "mov ax, " + n.getIzquierdo().getDato() + "\n";
                    emuLocal += "mov bx, " + n.getDerecho().getDato() + "\n";
                    emuLocal += "add ax,bx\n\n";
                    break;

                case "-":
                    System.out.println("sub");
                    izq = n.getIzquierdo().getDato();
                    der = n.getDerecho().getDato();

                    emuLocal += "mov ax, " + n.getIzquierdo().getDato() + "\n";
                    emuLocal += "mov bx, " + n.getDerecho().getDato() + "\n";
                    emuLocal += "sub ax,bx\n\n";
                    break;

                case "/":
                    System.out.println("div");
                    izq = n.getIzquierdo().getDato();
                    der = n.getDerecho().getDato();

                    emuLocal += "mov ax, " + n.getIzquierdo().getDato() + "\n";
                    emuLocal += "mov bx, " + n.getDerecho().getDato() + "\n";
                    emuLocal += "xor dx,dx\n";
                    emuLocal += "div bx\n\n";
                    break;

                case "*":
                    System.out.println("mul");
                    izq = n.getIzquierdo().getDato();
                    der = n.getDerecho().getDato();

                    emuLocal += "mov ax, " + n.getIzquierdo().getDato() + "\n";
                    emuLocal += "mov bx, " + n.getDerecho().getDato() + "\n";
                    emuLocal += "mul bx\n\n";
                    break;
            }// fin switch
        }// if
    }// generarEmuLocal

    public void generaEmutasm(String emu, int i) {
        try {
            FileWriter escritor = new FileWriter("e" + i + ".asm");
            escritor.write(emu);
            escritor.close();
            System.out.println("Archivo creado exitosamente");
        } catch (Exception e) {
            System.out.println("Ha ocurrido un error al crear el archivo");
        }
    }// generaEmutasm

    public void sonido() {
        try {
            File sonido = new File("src/arbolE/sonido.wav");

            if (sonido.exists()) {
                AudioInputStream audioStream = AudioSystem.getAudioInputStream(sonido);
                Clip clip = AudioSystem.getClip();
                clip.open(audioStream);
                clip.start();
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró el archivo de sonido.");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al reproducir el sonido.");
        }
    }

    public void abrirEnEmu8086(String nombreArchivo) {
        try {
            File archivoAsm = new File(nombreArchivo);

            if (!archivoAsm.exists()) {
                JOptionPane.showMessageDialog(
                        this,
                        "No se encontró el archivo ASM:\n"
                        + archivoAsm.getAbsolutePath()
                );
                return;
            }

            String rutaEmu8086 = "C:\\emu8086\\emu8086.exe";

            File ejecutableEmu8086 = new File(rutaEmu8086);

            if (!ejecutableEmu8086.exists()) {
                JOptionPane.showMessageDialog(
                        this,
                        "No se encontró EMU8086 en:\n"
                        + rutaEmu8086
                        + "\n\nModifica la variable rutaEmu8086 con la ubicación correcta."
                );
                return;
            }

            ProcessBuilder proceso = new ProcessBuilder(
                    ejecutableEmu8086.getAbsolutePath(),
                    archivoAsm.getAbsolutePath()
            );

            proceso.start();

        } catch (IOException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "No se pudo abrir el archivo en EMU8086:\n"
                    + e.getMessage()
            );
        }
    }

    public Nodo getArbolExpresion() {
        return arbolExpresion;
    }

    public void setArbolExpresion(Nodo arbolExpresion) {
        this.arbolExpresion = arbolExpresion;
    }

    private void btnOptimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOptimizarActionPerformed
        File video = new File("Chat.mp4");
        try {
            Desktop.getDesktop().open(video);
        } catch (IOException ex) {
            System.out.println("No se encontro video :C");
        }
    }//GEN-LAST:event_btnOptimizarActionPerformed

    private void btnCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodigoActionPerformed
        txtCodigo3Dir.setText("");
        temp = 0;
        String datos = "";
        ArbolJesusEspinosa arbol = new ArbolJesusEspinosa();
        datos = txtExpresion.getText();
        Nodo arbolExpresion = arbol.crear(datos); //Enviar los datos al árbol- expresión

        intermedio(arbolExpresion);
        txtCodigo3Dir.append(arbolExpresion.getCodigoIntermedio());
    }//GEN-LAST:event_btnCodigoActionPerformed

    private void btnGDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGDAActionPerformed
        String datos = txtExpresion.getText().trim();
        if (datos.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingresa una expresión antes de generar el GDA.");
            return;
        }

        if (arbolIA == null) {
            arbolIA = new ArbolIA();
        }

        Nodo arbolExpresion = arbolIA.crear(datos);
        Nodo raizGDA = arbolIA.convertirAGAD(arbolExpresion);

        JFrame ventanaGDA = new JFrame("Grafo dirigido acíclico - LyA2");
        PanelGrafo panelGDA = new PanelGrafo(
                raizGDA,
                new java.awt.Color(230, 240, 255),
                25,
                java.awt.Color.BLACK,
                2.0f
        );

        ventanaGDA.add(panelGDA);
        ventanaGDA.setSize(800, 600);
        ventanaGDA.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ventanaGDA.setLocationRelativeTo(this);
        ventanaGDA.setVisible(true);
    }//GEN-LAST:event_btnGDAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new FrameInterfaz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgenteIA;
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnCodigo;
    private javax.swing.JButton btnCompilar;
    private javax.swing.JButton btnGDA;
    private javax.swing.JButton btnOptimizar;
    private javax.swing.JButton btnTabla;
    private Componentes.ImagenRedondeada imgFoto;
    private Componentes.ImagenRedondeada imgLogoCiscoScript;
    private Componentes.ImagenRedondeada imgLogoPato;
    private Componentes.ImagenRedondeada imgLogoTec;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblExpresion;
    private javax.swing.JLabel lblIn;
    private javax.swing.JLabel lblNotacion;
    private javax.swing.JLabel lblPost;
    private javax.swing.JLabel lblPre;
    private javax.swing.JLabel lblReglas;
    private javax.swing.JLabel lblTítulo;
    private javax.swing.JPanel pnlInferior;
    private javax.swing.JPanel pnlMedio;
    private javax.swing.JPanel pnlSuperior;
    private javax.swing.JTextArea txtCodigo3Dir;
    private javax.swing.JTextField txtExpresion;
    private javax.swing.JTextArea txtInOrder;
    private javax.swing.JTextField txtNotacion;
    private javax.swing.JTextArea txtPostOrden;
    private javax.swing.JTextArea txtPreOrder;
    private javax.swing.JTextArea txtReglas;
    // End of variables declaration//GEN-END:variables
}
