/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package arbolE;

/**
 *
 * @author jesus
 */
public class FrameInterfaz extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameInterfaz.class.getName());

    /**
     * Creates new form FrameInterfaz
     */
    public FrameInterfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblExpresion = new javax.swing.JLabel();
        txtExpresion = new javax.swing.JTextField();
        btnCompilar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPreOrder = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCodigo3Secc = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtInOrder = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtPostOrden = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtReglas = new javax.swing.JTextArea();
        pnlSuperior = new javax.swing.JPanel();
        imgLogoTec = new Componentes.ImagenRedondeada();
        lblTítulo = new javax.swing.JLabel();
        imgFoto = new Componentes.ImagenRedondeada();
        imgLogoCiscoScript = new Componentes.ImagenRedondeada();
        imgLogoPato = new Componentes.ImagenRedondeada();
        pnlMedio = new javax.swing.JPanel();
        lblIn = new javax.swing.JLabel();
        lblPre = new javax.swing.JLabel();
        lblPost = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblReglas = new javax.swing.JLabel();
        pnlInferior = new javax.swing.JPanel();
        lblNotacion = new javax.swing.JLabel();
        txtNotacion = new javax.swing.JTextField();
        btnCodigo = new javax.swing.JButton();
        btnClean = new javax.swing.JButton();
        btnTabla = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblExpresion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblExpresion.setText("Expresión");

        txtExpresion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnCompilar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCompilar.setText("Compilar");
        btnCompilar.addActionListener(this::btnCompilarActionPerformed);

        txtPreOrder.setColumns(20);
        txtPreOrder.setRows(5);
        jScrollPane1.setViewportView(txtPreOrder);

        txtCodigo3Secc.setColumns(20);
        txtCodigo3Secc.setRows(5);
        jScrollPane2.setViewportView(txtCodigo3Secc);

        txtInOrder.setColumns(20);
        txtInOrder.setRows(5);
        jScrollPane3.setViewportView(txtInOrder);

        txtPostOrden.setColumns(20);
        txtPostOrden.setRows(5);
        jScrollPane4.setViewportView(txtPostOrden);

        txtReglas.setColumns(20);
        txtReglas.setRows(5);
        jScrollPane5.setViewportView(txtReglas);

        pnlSuperior.setBackground(new java.awt.Color(153, 153, 153));

        imgLogoTec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arbolE/escudo_itt_grande.png"))); // NOI18N

        lblTítulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTítulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTítulo.setText("Árbol de expresiones - LyA II");

        imgFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arbolE/Foto.png"))); // NOI18N

        imgLogoCiscoScript.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arbolE/Logo CiscoS.jpg"))); // NOI18N

        imgLogoPato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arbolE/Logo.png"))); // NOI18N

        javax.swing.GroupLayout pnlSuperiorLayout = new javax.swing.GroupLayout(pnlSuperior);
        pnlSuperior.setLayout(pnlSuperiorLayout);
        pnlSuperiorLayout.setHorizontalGroup(
            pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgLogoTec, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141)
                .addComponent(lblTítulo, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imgLogoPato, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(imgLogoCiscoScript, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(imgFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        pnlSuperiorLayout.setVerticalGroup(
            pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSuperiorLayout.createSequentialGroup()
                .addGroup(pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSuperiorLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblTítulo))
                    .addGroup(pnlSuperiorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(imgLogoTec, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSuperiorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imgLogoCiscoScript, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imgLogoPato, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imgFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMedio.setBackground(new java.awt.Color(255, 204, 51));

        lblIn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblIn.setText("In Orden");

        lblPre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPre.setText("Pre Orden");

        lblPost.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPost.setText("Post Orden");

        lblCodigo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCodigo.setText("Código 3 direcciones");

        lblReglas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblReglas.setText("Reglas semánticas");

        javax.swing.GroupLayout pnlMedioLayout = new javax.swing.GroupLayout(pnlMedio);
        pnlMedio.setLayout(pnlMedioLayout);
        pnlMedioLayout.setHorizontalGroup(
            pnlMedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMedioLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblPre, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addComponent(lblIn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(lblPost)
                .addGap(98, 98, 98)
                .addComponent(lblReglas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCodigo)
                .addGap(84, 84, 84))
        );
        pnlMedioLayout.setVerticalGroup(
            pnlMedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMedioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMedioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIn)
                    .addComponent(lblPre)
                    .addComponent(lblPost)
                    .addComponent(lblCodigo)
                    .addComponent(lblReglas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlInferior.setBackground(new java.awt.Color(0, 0, 0));

        lblNotacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNotacion.setForeground(new java.awt.Color(255, 255, 255));
        lblNotacion.setText("Notacion Polaca");

        txtNotacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnCodigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCodigo.setText("Código de 3 direcciones");

        btnClean.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnClean.setText("Clean");
        btnClean.addActionListener(this::btnCleanActionPerformed);

        btnTabla.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTabla.setText("Tabla de símbolos");
        btnTabla.addActionListener(this::btnTablaActionPerformed);

        javax.swing.GroupLayout pnlInferiorLayout = new javax.swing.GroupLayout(pnlInferior);
        pnlInferior.setLayout(pnlInferiorLayout);
        pnlInferiorLayout.setHorizontalGroup(
            pnlInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInferiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNotacion, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtNotacion, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnCodigo)
                .addGap(53, 53, 53)
                .addComponent(btnClean, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(btnTabla)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlInferiorLayout.setVerticalGroup(
            pnlInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInferiorLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(pnlInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNotacion)
                    .addComponent(txtNotacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCodigo)
                    .addComponent(btnClean)
                    .addComponent(btnTabla))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(lblExpresion, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtExpresion, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCompilar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
            .addComponent(pnlSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMedio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlInferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtExpresion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCompilar))
                    .addComponent(lblExpresion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(pnlMedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCleanActionPerformed

    private void btnTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTablaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTablaActionPerformed

    private void btnCompilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompilarActionPerformed
        String datos="";
        ArbolJesusEspinosa a = new ArbolJesusEspinosa();
        datos = txtExpresion.getText();
        
        Nodo arbolExpresion=a.crear(datos);
        txtReglas.setText("");
        txtReglas.append(a.getReglasEjecutadas());
    }//GEN-LAST:event_btnCompilarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new FrameInterfaz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnCodigo;
    private javax.swing.JButton btnCompilar;
    private javax.swing.JButton btnTabla;
    private Componentes.ImagenRedondeada imgFoto;
    private Componentes.ImagenRedondeada imgLogoCiscoScript;
    private Componentes.ImagenRedondeada imgLogoPato;
    private Componentes.ImagenRedondeada imgLogoTec;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblExpresion;
    private javax.swing.JLabel lblIn;
    private javax.swing.JLabel lblNotacion;
    private javax.swing.JLabel lblPost;
    private javax.swing.JLabel lblPre;
    private javax.swing.JLabel lblReglas;
    private javax.swing.JLabel lblTítulo;
    private javax.swing.JPanel pnlInferior;
    private javax.swing.JPanel pnlMedio;
    private javax.swing.JPanel pnlSuperior;
    private javax.swing.JTextArea txtCodigo3Secc;
    private javax.swing.JTextField txtExpresion;
    private javax.swing.JTextArea txtInOrder;
    private javax.swing.JTextField txtNotacion;
    private javax.swing.JTextArea txtPostOrden;
    private javax.swing.JTextArea txtPreOrder;
    private javax.swing.JTextArea txtReglas;
    // End of variables declaration//GEN-END:variables
}
